/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "proxy_constants.h"

namespace accumulo {

const proxyConstants g_proxy_constants;

proxyConstants::proxyConstants() {
}

} // namespace

