package:
    name: thrift
    version: "0.9.3"

source:
    fn: thrift-0.9.3.tar.gz
    url: http://www.us.apache.org/dist/thrift/0.9.3/thrift-0.9.3.tar.gz

requirements:
    build:
        - openssl
        - boost 1.57.0 [osx]
        - boost 1.60.0 [not osx]
    run:
