package:
  name: iopro
  version: "1.9.0"

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python 
    - numpy
    - cython
    - unixodbc [linux]
    - zlib
    - pcre
    - mongo-driver
    - postgresql 9.1.4
    - boost
    - thrift 0.9.3
  run:
    - python 
    - numpy
    - pandas
    - six
    - ordereddict     [py26]
    - unixodbc [linux]
    - mongo-driver
    - postgresql 9.1.4
    - boost
    - thrift 0.9.3

test:
  requires:
    - nose
    - pytest
  imports:
    - iopro.accumuloadapter.AccumuloAdapter
    - iopro.postgresadapter.PostgresAdapter
    - iopro.mongoadapter.MongoAdapter
    - iopro.textadapter.TextAdapter
    - iopro.pyodbc

about:
  home: http://www.continuum.io/
  license: proprietary - Continuum Analytics, Inc.
  license_family: Proprietary
  summary: python interface for databases, NoSQL stores, Amazon S3, and large data files
