package:
  name: textadapter
  version: "2.0.0"

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - cython

    # zlib and pcre versions pinned to fix shared library issues
    - zlib 1.2.8
    - pcre 8.31

  run:
    - python
    - numpy
    - pandas
    - six
    - ordereddict     [py26]

test:
  requires:
    - nose
    - pytest

  imports:
    - textadapter
    - textadapter.core.TextAdapter

about:
  home: https://github.com/ContinuumIO/TextAdapter
  license: BSD
  summary: python interface Amazon S3, and large data files
