package:
  name: TextAdapter
  version: "2.0.0"

source:
  path: ../../

build:
  number: 0

requirements:
  build:
    - python 
    - numpy
    - cython
    - zlib
    - pcre
    - boost
    - thrift 0.9.3
  run:
    - python 
    - numpy
    - pandas
    - six
    - ordereddict     [py26]
    - boost
    - thrift 0.9.3

test:
  requires:
    - nose
    - pytest
  imports:
    - TextAdapter.textadapter.TextAdapter

about:
  home: https://github.com/ContinuumIO/TextAdapter
  license: BSD
  summary: python interface Amazon S3, and large data files
