#!/bin/bash

PYTHON_VERSION=2.7

if [ "${PYTHON_VERSION}" == "" ]; then
    echo You must select a Python version with the PYTHON_VERSION variable.
    exit 1
fi

# Start from scratch
if [ -d build ]; then
    rm -rf build
fi
mkdir build
cd build

# Use conda to create a conda environment of the required
# python version and containing the dependencies.
export PYENV_PREFIX=${WORKSPACE}/build/pyenv
rm -rf ${PYENV_PREFIX}
~/anaconda/bin/conda create --yes -p ${PYENV_PREFIX} anaconda python=${PYTHON_VERSION} numpy=1.7 || exit 1
export PATH=${PYENV_PREFIX}/bin:${PATH}

# JNB: Get rid of any iopro that conda may have installed
rm -rf ${PYENV_PREFIX}/lib/python2.7/site-packages/iopro*

# Get and build pcre lib
if [ ! -f ${WORKSPACE}/pcre-8.30.tar.gz ]; then
    cd ..
    wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.30.tar.gz
    cd build
fi

tar -zxvf ../pcre-8.30.tar.gz
cd pcre-8.30
./configure
make
cd ..

# Get and build gzip compression lib
if [ ! -f ${WORKSPACE}/zlib-1.2.7.tar.bz2 ]; then
    cd ..
    wget http://downloads.sourceforge.net/project/libpng/zlib/1.2.7/zlib-1.2.7.tar.bz2
    cd build
fi

tar -jxvf ../zlib-1.2.7.tar.bz2
cd zlib-1.2.7
./configure
make
cd ..


# Set up include and lib paths since we're not installing in default system paths
export IOPRO_INCLUDE_PATH=${WORKSPACE}/build/pcre-8.30:$IOPRO_INCLUDE_PATH
export IOPRO_LIBRARY_PATH=${WORKSPACE}/build/pcre-8.30/.libs:$IOPRO_LIBRARY_PATH
export IOPRO_INCLUDE_PATH=${WORKSPACE}/build/zlib-1.2.7:$IOPRO_INCLUDE_PATH
export IOPRO_LIBRARY_PATH=${WORKSPACE}/build/zlib-1.2.7:$IOPRO_LIBRARY_PATH
export IOPRO_INCLUDE_PATH=~/anaconda/include/python${PYTHON_VERSION}:$IOPRO_INCLUDE_PATH
export IOPRO_LIBRARY_PATH=~/anaconda/lib:$IOPRO_LIBRARY_PATH

export LD_LIBRARY_PATH=${WORKSPACE}/build/pcre-8.30/.libs:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=${WORKSPACE}/build/zlib-1.2.7:$LD_LIBRARY_PATH

cd ..
python setup.py build_ext --inplace --include-dirs=$IOPRO_INCLUDE_PATH --library-dirs=$IOPRO_LIBRARY_PATH || exit 1
python -c 'import textadapter; import sys; sys.exit(1 - textadapter.test(num_records=1000))'
